### PR TITLE
test names, return values

### PR DESCRIPTION
**Pull request by amoore**
I hope you're still interested in improvements to this module!

Here are a few patches that have helped me use this module as tests for my DNS. The main improvements are: allowing tests to be named regardless of whether they are tests or one or multiple records, and returning a false value if the test fails.

### CODE REVIEW

**Comment by xsawyerx** [comment]
I apologize for not seeing this earlier. I will try to review these changes this week and apply them as necessary, releasing a new version soon after.

**Comment by xsawyerx** [comment]
I just reviewed all commits. Two of them I implemented in a different way. I intend to make a few more improvements to this and then release it. (It's not every day that you realize something you wrote for $work over 9 years ago is used by someone, and they are offering improvements!) :)

**Comment by amoore** [comment]
Thanks for incorporating these changes. They'll help me keep track of my thousands of DNS records!
I think I can close this pull request since they're in master now.

**Comment by xsawyerx** [comment]
The reason I didn't close this ticket is that I haven't released the new version yet. I'll keep this ticket posted once I do.

**Comment by xsawyerx** [comment]
Just released a new version!

Some updates you should know (that are also included in the Changes file):

* I made the attributes (`nameservers`, `object`, `follow_cname`, and `warnings`) immutable. That means that they can only receive a value when set in the `new` constructor.
* This means you cannot override the nameservers once you instantiated an object. You will need a new object.

Please open additional tickets if you encounter anything or need any feature. I'll try to also remove the Set::Object dependency since I can just replace it with a quick hash.

If you don't get a response from me here, hit me up at xsawyerx AT cpan YOUKNOWTHEREST. :)

**Pull request closed without merging**
